### ISSUE TITLE
helm stable repo in loft is using the now depricated url

### ISSUE THREAD

**Issue by blairham** [loft-sh/loft#72] opened 2020-11-18 14:24 UTC
Currently, you can not update helm apps due to the now deprecated URL. According to [this article ](https://www.cncf.io/blog/2020/10/07/important-reminder-for-all-helm-users-stable-incubator-repos-are-deprecated-and-all-images-are-changing-location/) on November 13th, the old repos are now deprecated.

*Expected Results*
Installing/Upgrading an app through loft should continue to work.

**Comment by FabianKramm** [comment] 2020-11-23 11:53
@blairham thanks for opening this issue! What is the error that you are receiving? Currently the stable repo is still listed in our app repo list, however we will remove that eventually. If you want to change the repository of an installed app, you can go to `Clusters` -> `Apps` and click on the `Show Yaml` button. Then change the repository URL in the spec section:

```yaml
apiVersion: cluster.loft.sh/v1
kind: HelmRelease
metadata:
  ...
spec:
  chart:
    name: docker-registry
    version: 1.9.6 <- Change this to the new version
    repoURL: 'https://kubernetes-charts.storage.googleapis.com' <- Change this URL to the new repo URL
status:
  ...
```

Then press update and loft will change the repo and version of the app. We cannot do this automatically since we don't know for each chart how the new repository is called, hence why you need to update this manually.

**Comment by blairham** [comment] 2020-11-23 17:13
@FabianKramm here is the error I get:

Error: error executing helm upgrade metrics-server metrics-server --repo https://kubernetes-charts.storage.googleapis.com --version 2.11.4 --kubeconfig /tmp/737422969 --namespace kube-system --install --values /tmp/486389636: Error: failed to download "https://charts.helm.sh/stable/metrics-server-2.11.4.tgz" (hint: running `helm repo update` may help)


I've already changed the repo, through the edit yaml to `https://charts.helm.sh/stable` which works

**Comment by FabianKramm** [comment] 2020-11-26 08:55
@blairham the problem is that some paths are wrong currently in the stable helm repo (if you click on the link you'll notice the file actually doesn't exist, thats why you get this error). We'll add an option soon to define custom chart repos easier.

**Comment by blairham** [comment] 2020-11-28 17:53
@FabianKramm yeah that is due to the deprication of the stable repo ;) they moved it to https://charts.helm.sh/stable from https://kubernetes-charts.storage.googleapis.com

**Comment by carlmontanari** [comment] 2022-11-02 19:31
I think all of this should be sorted out at this point, so I'm going to close this one out. Please feel free to re-open/open up a new issue if there are some lingering problems here!

**Closed by carlmontanari** 2022-11-02 19:31 UTC
Labels: enhancement, feature, needs-information
