### ISSUE TITLE
Can't go past the "Complete your profile" page

### ISSUE THREAD

**Issue by rajish** [loft-sh/loft#113] opened 2021-05-02 13:54 UTC
Submitting the form on the "Complete your profile" page spins the "Finish" button indefinitely. The loft pod logs say:
```
loft-6b647d94dc-ld6tl manager 2021-05-02 12:47:41.819818 I | http: TLS handshake error from 127.0.0.1:57608: remote error: tls: unknown certificate
```
I have TLS disabled in the `values.yaml`:

```
# TLS configuration with a custom cert and key
# Make sure the secret exists prior to deploying loft,
# otherwise the loft pod will not be able to start
tls:
  enabled: false
  secret: loft-tls
  crtKey: tls.crt
  keyKey: tls.key

...
ingress:
...
  tls:
    enabled: false
    secret: tls-loft
    clusterIssuer: lets-encrypt-http-issuer
```

**Comment by FabianKramm** [comment] 2021-05-04 10:42
@rajish thanks for creating this issue! Are there any other logs? Are you running loft in a private cluster? The TLS handshare error is usually unrelated and occurs if you are using a self signed certificate that you have to accept in the browser first. However this shouldn't lead to a stuck "Finish" button

**Comment by rajish** [comment] 2021-05-04 13:36
Yes, I'm trying to run loft on a private cluster. When I deleted it and installed it again the TLS messages stopped appearing, but the "spinning" problem persists.

I think it can have something to do with #112 as the cluster runs on AWS.

**Comment by FabianKramm** [comment] 2021-05-05 09:48
@rajish thanks for the information! Usually the problem with private clusters is that you have to ensure that the following ports on the nodes are reachable because the kubernetes master needs to be able to communicate with the loft and kiosk pods directly (see [our docs](https://loft.sh/docs/guides/administration/air-gapped-installation#install-loft-into-the-cluster) for more info):
- 8888 (loft api service extension)
- 8443 (kiosk api service extension)
- 9443 (kiosk webhook & loft webhook)

In your case the problem is probably a hanging admission webhook as the Kubernetes master cannot reach the nodes subnet on one of the above mentioned ports. You can also take a look at our [troubleshooting section](https://loft.sh/docs/guides/troubleshooting#error-failed-calling-webhook-validateloftsh-post-xxxvalidatetimeout10s-context-deadline-exceeded-internalerror) that describes this problem as well.

**Comment by carlmontanari** [comment] 2022-08-19 18:24
Going to close this out as its a bit old, but feel free to reopen if there are still issues here!

**Closed by carlmontanari** 2022-08-19 18:24 UTC
