### ISSUE TITLE
Helm: Loft deadlocks install if transient failure

### ISSUE THREAD

**Issue by withinboredom** [loft-sh/loft#169] opened 2021-12-10 06:49 UTC
During a loft installation via helm, there was a transient failure:

```
Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://nginx-ingress-nginx-controller-admission.ingress.svc:443/networking/v1/ingresses?timeout=10s": context deadline exceeded
```

Rerunning the helm command just ends up with this error:

```
Error: failed pre-install: warning: Hook pre-install loft/templates/admin/user.yaml failed: object is being deleted: users.storage.loft.sh "admin" already exists
```

which results in a single loft-agent pod, no other loft pods.

Here's the values for the helm chart fwiw:

```
    admin:
      create: true
      username: admin
      password: PASSWORD
    ingress:
      enabled: true
      name: loft-ingress
      host: DOMAIN
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        enabled: true
        secret: tls-loft
```

`loft start` was able to resolve the issue.

**Comment by FabianKramm** [comment] 2021-12-10 12:56
@withinboredom thanks for creating this issue! The problem is probably the finalizer on the user object, which is needed to cleanup user resources. We might think about running a cleanup hook though that removes things like that when you use helm.

**Comment by withinboredom** [comment] 2021-12-10 13:06
NP, you guys have built a fantastic product!

**Comment by FabianKramm** [comment] 2021-12-10 13:26
@withinboredom thanks a lot for the kind words, glad you like it!

**Comment by carlmontanari** [comment] 2022-11-02 21:05
I think that `loft start` sorted this out as it looks like it nukes the admin user prior to redeploying (via helm), so that probably aligns with the finalizer comment above. I think/hope this is OK (and is quite old) so I'll close this out, but please re-open if this is still an issue!

**Closed by carlmontanari** 2022-11-02 21:05 UTC
Labels: kind/bug
